export enum TransactionCommand {
  CREATE_VAULT = 'CREATE_VAULT',
  DEPOSIT_TO_VAULT = 'DEPOSIT_TO_VAULT',
  TAKE_LOAN = 'TAKE_LOAN',
  POOL_ADD_LIQUIDITY = 'POOL_ADD_LIQUIDITY',
  PAYBACK_LOAN = 'PAYBACK_LOAN',
  WITHDRAW_FROM_VAULT = 'WITHDRAW_FROM_VAULT',
  ACCOUNT_TO_ACCOUNT = 'ACCOUNT_TO_ACCOUNT',
  POOL_REMOVE_LIQUIDITY = 'POOL_REMOVE_LIQUIDITY',
  COMPOSITE_SWAP = 'COMPOSITE_SWAP',
}
