export enum TransactionType {
  // staking
  CREATE_MASTERNODE = 'CREATE_MASTERNODE',
  RESIGN_MASTERNODE = 'RESIGN_MASTERNODE',
  SEND_FROM_LIQ = 'SEND_FROM_LIQ',
  SEND_TO_LIQ = 'SEND_TO_LIQ',
  WITHDRAWAL = 'WITHDRAWAL',

  // utxo management
  UTXO_MERGE = 'UTXO_MERGE',
  UTXO_SPLIT = 'UTXO_SPLIT',

  // yield machine
  CREATE_VAULT = 'CREATE_VAULT',
  DEPOSIT_TO_VAULT = 'DEPOSIT_TO_VAULT',
  TAKE_LOAN = 'TAKE_LOAN',
  POOL_ADD_LIQUIDITY = 'POOL_ADD_LIQUIDITY',
  PAYBACK_LOAN = 'PAYBACK_LOAN',
  WITHDRAW_FROM_VAULT = 'WITHDRAW_FROM_VAULT',
  POOL_REMOVE_LIQUIDITY = 'POOL_REMOVE_LIQUIDITY',

  // general
  ACCOUNT_TO_ACCOUNT = 'ACCOUNT_TO_ACCOUNT',
  COMPOSITE_SWAP = 'COMPOSITE_SWAP',
}
