name: API STG CI/CD

on:
  push:
    branches: [staging]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: app-lock-api-stg
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '16.x'

jobs:
  build-and-deploy:
    name: Build, test and deploy to STG
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install packages
        run: |
          npm ci

      - name: Build code
        run: |
          npm run build

      - name: Run tests
        run: |
          npm run test

      - name: Run linter
        run: |
          npm run lint

      - name: Deploy to Azure App Service (STG)
        uses: azure/webapps-deploy@0b651ed7546ecfc75024011f76944cb9b381ef1e
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.STG_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
